### ISSUE TITLE
[BUG] Yoda uses two sources of truth for its metadata

### ISSUE THREAD

**Issue by chStaiger** [UtrechtUniversity/yoda-ansible#413] opened 2024-04-29 09:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Metadata for collections can be manipulated through the Yoda portal but also directly in the iCAT by employing the icommands or any other iRODS API.
When metadata is altered trough the webportal the changes are synchronised with the iCAT. However, the metadata is not synchronised from the the iCAT to the frontent leading to different information in the two sources.

Effect: For the Archiving the metadata in the portal/metadata.json is the source of truth and the altered iCAT metadata corresponding to the portal information is forgotten. For the Search the metadata in the iCAT is the source of truth leading to wrong search results for portal users.

### Expected Behavior

There needs to be one source of truth for the metadata for all Yoda processes and features.

Either synchronse the respective metadata from the iCAT to the portal when metadata keys which are also used by Yoda  are changed through the icommands or any other API. Or protect the metadata keys in the iCAT to which you map the portal metadata such that they can only be written through the portal.

### Steps To Reproduce

1. I am using Yoda 1.9
2. Create a collection 'Test_metadata' and annotate it through the portal with the title 'TEST_TITLE_CS'
3. Test in the portal that you can find the collection by typing in 'TEST_TITLE_CS'
4. Change e.g. the title of the collection with the icommands `imeta set  -C Test_metadata Title blabla` or use an iRODS API of your choice to manipulate the title
5. Check the metadata in the portal and try your search again in the portal --> collection is no longer listed
6. Archive your data --> The new title is ignored

### Environment

```markdown
- Yoda: 1.9, SURF instance https://surf-yoda.irods.surfsara.nl/
- Ansible: N/A
- Operating System:N/A
- Browser:N/A
```

**Comment by chStaiger** [comment] 2024-04-29 09:04
Linked to #44

**Comment by Danny-dK** [comment] 2024-04-30 09:39
I know far too little about this, but is this a helper?:

![image](https://github.com/UtrechtUniversity/yoda/assets/45395070/c3db1bf8-bfe7-4f66-a68d-8988c5f8005e)

https://github.com/MaastrichtUniversity/irods_avu_json-ruleset
Though I don't know whether "not allowed" means you'll get an error warning stating you're not allowed to adjust (or whether no error is given).
Perhaps then specifically prepending the attribute names with 'yoda' (eg Yoda_Title, Yoda_Affiliation_Name, etc), may allow easier protecting of adjusting avu's (for those that don't want to modify the yoda-metadata.json and just want to add avu's in iRODS for whatever reason).

**Comment by chStaiger** [comment] 2024-05-02 09:06
> I know far too little about this, but is this a helper?:
> 
> ![image](https://private-user-images.githubusercontent.com/45395070/326748401-c3db1bf8-bfe7-4f66-a68d-8988c5f8005e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDA5ODEsIm5iZiI6MTcxNDY0MDY4MSwicGF0aCI6Ii80NTM5NTA3MC8zMjY3NDg0MDEtYzNkYjFiZjgtYmZlNy00ZjY2LWE2OGQtODk4OGM1ZjgwMDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA5MDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZDk1NWZlMGQ1NzdlZTJkMWZlYWQ0ZTNhYjFlMDliMWI2YzJmYzQzZjQ3YzYwNjQ1MTMxNzkyZjRmMTlhY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NC4gm6iDRLlq7DDs_9pUpDEdbl9Mhl-xz6P2cMgxdLM)
> 
> https://github.com/MaastrichtUniversity/irods_avu_json-ruleset Though I don't know whether "not allowed" means you'll get an error warning stating you're not allowed to adjust (or whether no error is given). Perhaps then specifically prepending the attribute names with 'yoda' (eg Yoda_Title, Yoda_Affiliation_Name, etc), may allow easier protecting of adjusting avu's (for those that don't want to modify the yoda-metadata.json and just want to add avu's in iRODS for whatever reason).

I think this is exaclty what we need to ensure the Yoda processes while still giving flexibility to our users to define their own metadata.

**Comment by lwesterhof** [comment] 2024-06-28 12:02
Duplicate of https://github.com/UtrechtUniversity/yoda/issues/44

**Closed as completed by lwesterhof** 2024-06-28 12:02 UTC
